### ISSUE TITLE
Get "http://localhost:9000/a-bucket/?location=": dial tcp [::1]:9000: connect: connection refused

### ISSUE THREAD

**Issue by chandrakalagowda** [zilliztech/milvus-backup#174]
milvus-backup did not work on mac Ventura 13.3.1. Please help me to debug.

docker Version:  0.19.0
Milvus version : 2.2.10

====
git clone https://github.com/zilliztech/milvus-backup.git
====

(.milvusenv) www.abcom.in milvus/milvus-backup [main]$ go get
go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead.

If the above message needs to be taken care of .....  Where and which files do I need to modify.
====

(.milvusenv) www.abcom.in milvus/milvus-backup [main]$ go build

(.milvusenv) www.abcom.in milvus/milvus-backup [main]$ ls
Dockerfile	build		configs		docs		go.sum		milvus-backup	tests
OWNERS		build.sh	core		example		internal	proto_gen_go.sh	ut_test.go
README.md	cmd		deployment	go.mod		main.go		scripts

====

(.milvusenv) www.abcom.in milvus/milvus-backup [main]$ ./milvus-backup create -n testbackup

The above command does not execute back up successfully. Generates a lot of connection refused messages. shown below
Please help me debug.
====
config:backup.yaml

[2023/08/01 17:27:33.690 +05:30] [INFO] [logutil/logutil.go:165] ["Log directory"] [configDir=]
[2023/08/01 17:27:33.691 +05:30] [INFO] [logutil/logutil.go:166] ["Set log file to "] [path=logs/backup.log]
[2023/08/01 17:27:33.691 +05:30] [INFO] [core/backup_impl_create_backup.go:25] ["receive CreateBackupRequest"] [requestId=9998b5e0-3062-11ee-a349-acde48001122] [backupName=testbackup] [collections="[]"] [databaseCollections=] [async=false]
[2023/08/01 17:27:33.693 +05:30] [WARN] [storage/minio_chunk_manager.go:97] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused"]
[2023/08/01 17:27:33.895 +05:30] [WARN] [storage/minio_chunk_manager.go:97] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused"]
[2023/08/01 17:27:34.297 +05:30] [WARN] [storage/minio_chunk_manager.go:97] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused"]
[2023/08/01 17:27:35.098 +05:30] [WARN] [storage/minio_chunk_manager.go:97] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused"]
[2023/08/01 17:27:36.700 +05:30] [WARN] [storage/minio_chunk_manager.go:97] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused"]
[2023/08/01 17:27:39.701 +05:30] [WARN] [storage/minio_chunk_manager.go:97] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused"]
[2023/08/01 17:27:42.704 +05:30] [WARN] [storage/minio_chunk_manager.go:97] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused"]
[2023/08/01 17:27:45.706 +05:30] [WARN] [storage/minio_chunk_manager.go:97] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused"]
[2023/08/01 17:27:48.708 +05:30] [WARN] [storage/minio_chunk_manager.go:97] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused"]
[2023/08/01 17:27:51.709 +05:30] [WARN] [storage/minio_chunk_manager.go:97] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused"]
[2023/08/01 17:27:54.719 +05:30] [WARN] [storage/minio_chunk_manager.go:97] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused"]
[2023/08/01 17:27:57.721 +05:30] [WARN] [storage/minio_chunk_manager.go:97] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused"]
[2023/08/01 17:28:00.724 +05:30] [WARN] [storage/minio_chunk_manager.go:97] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused"]
[2023/08/01 17:28:03.726 +05:30] [WARN] [storage/minio_chunk_manager.go:97] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused"]
[2023/08/01 17:28:06.729 +05:30] [WARN] [storage/minio_chunk_manager.go:97] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused"]
[2023/08/01 17:28:09.730 +05:30] [WARN] [storage/minio_chunk_manager.go:97] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused"]
[2023/08/01 17:28:12.732 +05:30] [WARN] [storage/minio_chunk_manager.go:97] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused"]
[2023/08/01 17:28:15.733 +05:30] [WARN] [storage/minio_chunk_manager.go:97] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused"]
[2023/08/01 17:28:18.736 +05:30] [WARN] [storage/minio_chunk_manager.go:97] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused"]
[2023/08/01 17:28:21.739 +05:30] [WARN] [storage/minio_chunk_manager.go:97] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused"]
[2023/08/01 17:28:24.740 +05:30] [ERROR] [core/backup_context.go:171] ["failed to initial storage client"] [error="All attempts results:\nattempt #1:Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused\nattempt #2:Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused\nattempt #3:Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused\nattempt #4:Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused\nattempt #5:Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused\nattempt #6:Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused\nattempt #7:Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused\nattempt #8:Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused\nattempt #9:Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused\nattempt #10:Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused\nattempt #11:Get \"http://localhost:9000/a-bucket/?location=\": dial tcp [::1]:9000: connect: connection refused\n"] [stack="github.com/zilliztech/milvus-backup/core.(*BackupContext).getStorageClient\n\t/Users/www.abcom.in/Documents/milvus/milvus-backup/core/backup_context.go:171\ngithub.com/zilliztech/milvus-backup/core.(*BackupContext).CreateBackup\n\t/Users/www.abcom.in/Documents/milvus/milvus-backup/core/backup_impl_create_backup.go:47\ngithub.com/zilliztech/milvus-backup/cmd.glob..func1\n\t/Users/www.abcom.in/Documents/milvus/milvus-backup/cmd/create.go:56\ngithub.com/spf13/cobra.(*Command).execute\n\t/Users/www.abcom.in/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/Users/www.abcom.in/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990\ngithub.com/spf13/cobra.(*Command).Execute\n\t/Users/www.abcom.in/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918\ngithub.com/zilliztech/milvus-backup/cmd.Execute\n\t/Users/www.abcom.in/Documents/milvus/milvus-backup/cmd/root.go:24\nmain.main\n\t/Users/www.abcom.in/Documents/milvus/milvus-backup/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"]
panic: All attempts results:
attempt #1:Get "http://localhost:9000/a-bucket/?location=": dial tcp [::1]:9000: connect: connection refused
attempt #2:Get "http://localhost:9000/a-bucket/?location=": dial tcp [::1]:9000: connect: connection refused
attempt #3:Get "http://localhost:9000/a-bucket/?location=": dial tcp [::1]:9000: connect: connection refused
attempt #4:Get "http://localhost:9000/a-bucket/?location=": dial tcp [::1]:9000: connect: connection refused
attempt #5:Get "http://localhost:9000/a-bucket/?location=": dial tcp [::1]:9000: connect: connection refused
attempt #6:Get "http://localhost:9000/a-bucket/?location=": dial tcp [::1]:9000: connect: connection refused
attempt #7:Get "http://localhost:9000/a-bucket/?location=": dial tcp [::1]:9000: connect: connection refused
attempt #8:Get "http://localhost:9000/a-bucket/?location=": dial tcp [::1]:9000: connect: connection refused
attempt #9:Get "http://localhost:9000/a-bucket/?location=": dial tcp [::1]:9000: connect: connection refused
attempt #10:Get "http://localhost:9000/a-bucket/?location=": dial tcp [::1]:9000: connect: connection refused
attempt #11:Get "http://localhost:9000/a-bucket/?location=": dial tcp [::1]:9000: connect: connection refused

goroutine 1 [running]:
github.com/zilliztech/milvus-backup/core.(*BackupContext).getStorageClient(0xc00016d340)
	/Users/www.abcom.in/Documents/milvus/milvus-backup/core/backup_context.go:172 +0x286
github.com/zilliztech/milvus-backup/core.(*BackupContext).CreateBackup(0xc00016d340, {0x1ee3450?, 0xc00011a010}, 0xc00045df10)
	/Users/www.abcom.in/Documents/milvus/milvus-backup/core/backup_impl_create_backup.go:47 +0x705
github.com/zilliztech/milvus-backup/cmd.glob..func1(0x2e93de0?, {0x1d16dcf?, 0x2?, 0x2?})
	/Users/www.abcom.in/Documents/milvus/milvus-backup/cmd/create.go:56 +0x4a5
github.com/spf13/cobra.(*Command).execute(0x2e93de0, {0xc0002a4b60, 0x2, 0x2})
	/Users/www.abcom.in/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0x2e94a60)
	/Users/www.abcom.in/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/www.abcom.in/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/zilliztech/milvus-backup/cmd.Execute()
	/Users/www.abcom.in/Documents/milvus/milvus-backup/cmd/root.go:24 +0x71
main.main()
	/Users/www.abcom.in/Documents/milvus/milvus-backup/main.go:17 +0x17
(.milvusenv) www.abcom.in milvus/milvus-backup [main]$         

=============
Below is my backup.yml file
=============
# Configures the system log output.
log:
  level: info # Only supports debug, info, warn, error, panic, or fatal. Default 'info'.
  console: true
  file:
    rootPath: "logs/backup.log"

http:
  simpleResponse: true

# milvus proxy address, compatible to milvus.yaml
milvus:
  address: localhost
  port: 19530
  authorizationEnabled: false
  # tls mode values [0, 1, 2]
  # 0 is close, 1 is one-way authentication, 2 is two-way authentication.
  tlsMode: 0
  user: "root"
  password: "Milvus"

# Related configuration of minio, which is responsible for data persistence for Milvus.
minio:
  address: localhost # Address of MinIO/S3
  port: 9000   # Port of MinIO/S3
  accessKeyID: minioadmin # accessKeyID of MinIO/S3
  secretAccessKey: minioadmin # MinIO/S3 encryption string
  useSSL: false # Access to MinIO/S3 with SSL
  useIAM: false
  cloudProvider: "aws"
  iamEndpoint: ""
  
  bucketName: "a-bucket" # Milvus Bucket name in MinIO/S3, make it the same as your milvus instance
  rootPath: "files" # Milvus storage root path in MinIO/S3, make it the same as your milvus instance

  backupBucketName: "a-bucket" # Bucket name to store backup data. Backup data will store to backupBucketName/backupRootPath
  backupRootPath: "backup" # Rootpath to store backup data. Backup data will store to backupBucketName/backupRootPath

backup:
  maxSegmentGroupSize: 2G

**Comment by zhuwenxing** [comment]
It looks like the backup tool can not connect to the minio.
How do you deploy the Milvus? Using docker-compose?
If so, can you share your `docker-compose.yaml` file, and use `docker ps` to show the container's status?

**Comment by chandrakalagowda** [comment]
> It looks like the backup tool can not connect to the minio. How do you deploy the Milvus? Using docker-compose? If so, can you share your `docker-compose.yaml` file, and use `docker ps` to show the container's status?

Yes I use docker-compose to deploy Milvus.

Here is my docker-compose.yaml
==
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  attu:
    container_name: attu
    image: zilliz/attu:v2.2.6
    environment:
      MILVUS_URL: milvus-standalone:19530
    ports:
      - "8000:3000"
    depends_on:
      - "standalone"


  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.10
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus

**Comment by chandrakalagowda** [comment]
<img width="970" alt="image" src="https://github.com/zilliztech/milvus-backup/assets/24473622/142e6f5a-30c7-4bc0-9d1b-576656e05e32">

**Comment by zhuwenxing** [comment]
![image](https://github.com/zilliztech/milvus-backup/assets/12268675/71d00b01-cf01-4266-b9d7-46eda7cb6448)

Well, that makes sense. In your docker-compose file, the 9000 port is not exposed.

You can modify your docker-compose file like the above.

**Comment by chandrakalagowda** [comment]
Thank you so much. It worked!.
I was unaware of this.

Thank you again for your time.

**Comment by ENg-122** [comment]
# 数据库的默认账号和密码仅首次运行时设置有效
# 如果修改了账号密码，记得改数据库和项目连接参数，别只改一处~
# 该配置文件只是给快速启动，测试使用。正式使用，记得务必修改账号密码，以及调整合适的知识库参数，共享内存等。
# 如何无法访问 dockerhub 和 git，可以用阿里云（阿里云没有arm包）

version: '3.3'
services:
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - '9001:9001'
      - '9000:9000'
    networks:
      - fastgpt
    volumes:
      - ./minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3
  # milvus
  milvusEtcd:
    container_name: milvusEtcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    networks:
      - fastgpt
    volumes:
      - ./milvus/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ['CMD', 'etcdctl', 'endpoint', 'health']
      interval: 30s
      timeout: 20s
      retries: 3
  milvusStandalone:
    container_name: milvusStandalone
    image: milvusdb/milvus:v2.4.3
    command: ['milvus', 'run', 'standalone']
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: milvusEtcd:2379
      MINIO_ADDRESS: minio:9000
    networks:
      - fastgpt
    volumes:
      - ./milvus/data:/var/lib/milvus
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9091/healthz']
      interval: 30s
      # start_period: 90s
      timeout: 20s
      retries: 3
    depends_on:
      - 'milvusEtcd'
      - 'minio'

  mongo:
    image: mongo:5.0.18
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18 # 阿里云
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - fastgpt
    command: mongod --keyFile /data/mongodb.key --replSet rs0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myusername
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - ./mongo/data:/data/db
    entrypoint:
      - bash
      - -c
      - |
        openssl rand -base64 128 > /data/mongodb.key
        chmod 400 /data/mongodb.key
        chown 999:999 /data/mongodb.key
        echo 'const isInited = rs.status().ok === 1
        if(!isInited){
          rs.initiate({
              _id: "rs0",
              members: [
                  { _id: 0, host: "mongo:27017" }
              ]
          })
        }' > /data/initReplicaSet.js
        # 启动MongoDB服务
        exec docker-entrypoint.sh "$$@" &

        # 等待MongoDB服务启动
        until mongo -u myusername -p mypassword --authenticationDatabase admin --eval "print('waited for connection')" > /dev/null 2>&1; do
          echo "Waiting for MongoDB to start..."
          sleep 2
        done

        # 执行初始化副本集的脚本
        mongo -u myusername -p mypassword --authenticationDatabase admin /data/initReplicaSet.js

        # 等待docker-entrypoint.sh脚本执行的MongoDB服务进程
        wait $$!

  # fastgpt
  sandbox:
    container_name: sandbox
    image: ghcr.io/labring/fastgpt-sandbox:v4.8.6 # git
    networks:
      - fastgpt
    restart: always
  fastgpt:
    container_name: fastgpt
    image: ghcr.io/labring/fastgpt:v4.8.6 # git
    ports:
      - 3000:3000
    networks:
      - fastgpt
    depends_on:
      - mongo
      - milvusStandalone
      - sandbox
    restart: always
    environment:
      # root 密码，用户名为: root。如果需要修改 root 密码，直接修改这个环境变量，并重启即可。
      - DEFAULT_ROOT_PSW=RCms@Zte3
      # AI模型的API地址哦。务必加 /v1。这里默认填写了OneApi的访问地址。
      - OPENAI_BASE_URL=http://10.56.135.208:3001/v1
      # AI模型的API Key。（这里默认填写了OneAPI的快速默认key，测试通后，务必及时修改）
      - CHAT_API_KEY=sk-iffsKb5MuFcZ9W350b32D83386B54cF59435Ed58E7E558E6
      # 数据库最大连接数
      - DB_MAX_LINK=30
      # 登录凭证密钥
      - TOKEN_KEY=any
      # root的密钥，常用于升级时候的初始化请求
      - ROOT_KEY=root_key
      # 文件阅读加密
      - FILE_TOKEN_KEY=filetoken
      # MongoDB 连接参数. 用户名myusername,密码mypassword。
      - MONGODB_URI=mongodb://myusername:mypassword@mongo:27017/fastgpt?authSource=admin
      # zilliz 连接参数
      - MILVUS_ADDRESS=http://milvusStandalone:19530
      - MILVUS_TOKEN=none
      # sandbox 地址
      - SANDBOX_URL=http://sandbox:3000
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    volumes:
      - ./config.json:/app/data/config.json

  # oneapi
  mysql:
    image: mysql:8.0.36
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - fastgpt
    command: --default-authentication-plugin=mysql_native_password
    environment:
      # 默认root密码，仅首次运行有效
      MYSQL_ROOT_PASSWORD: oneapimmysql
      MYSQL_DATABASE: oneapi
    volumes:
      - ./mysql:/var/lib/mysql
  oneapi:
    container_name: oneapi
    #image: oneapi:v1.0.1
    image: ghcr.io/songquanpeng/one-api:latest
    ports:
      - 3001:3000
    privileged: true
    depends_on:
      - mysql
    networks:
      - fastgpt
    restart: always
    environment:
      # mysql 连接参数
      - SQL_DSN=root:oneapimmysql@tcp(mysql:3306)/oneapi
      # 登录凭证加密密钥
      - SESSION_SECRET=oneapikey
      # 内存缓存
      - MEMORY_CACHE_ENABLED=true
      # 启动聚合更新，减少数据交互频率
      - BATCH_UPDATE_ENABLED=true
      # 聚合更新时长
      - BATCH_UPDATE_INTERVAL=10
      # 初始化的 root 密钥（建议部署完后更改，否则容易泄露）
      - INITIAL_ROOT_TOKEN=fastgpt
      # 修复无法获取gpt3.5令牌错误
      - TIKTOKEN_CACHE_DIR=/data/cache
    volumes:
      - ./oneapi:/data

  m3e-large-api:
    image: registry.cn-hangzhou.aliyuncs.com/fastgpt_docker/m3e-large-api:latest
    container_name: m3e-large-api
    restart: always
    privileged: true
    networks:
      - fastgpt
    ports:
      - 6008:6008
    environment:
      # 修复无法获取gpt3.5令牌错误
      - TIKTOKEN_CACHE_DIR=/data/cache
    volumes:
      - ./oneapi:/data


networks:
  fastgpt:
我的也不行 同样的报错 能帮忙看下吗？

**Comment by ENg-122** [comment]
version: '3.3'
services:
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - '9001:9001'
      - '9000:9000'
    networks:
      - fastgpt
    volumes:
      - ./minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3
  # milvus
  milvusEtcd:
    container_name: milvusEtcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    networks:
      - fastgpt
    volumes:
      - ./milvus/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ['CMD', 'etcdctl', 'endpoint', 'health']
      interval: 30s
      timeout: 20s
      retries: 3
  milvusStandalone:
    container_name: milvusStandalone
    image: milvusdb/milvus:v2.4.3
    command: ['milvus', 'run', 'standalone']
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: milvusEtcd:2379
      MINIO_ADDRESS: minio:9000
    networks:
      - fastgpt
    volumes:
      - ./milvus/data:/var/lib/milvus
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9091/healthz']
      interval: 30s
      # start_period: 90s
      timeout: 20s
      retries: 3
    depends_on:
      - 'milvusEtcd'
      - 'minio'

  mongo:
    image: mongo:5.0.18
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18 # 阿里云
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - fastgpt
    command: mongod --keyFile /data/mongodb.key --replSet rs0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myusername
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - ./mongo/data:/data/db
    entrypoint:
      - bash
      - -c
      - |
        openssl rand -base64 128 > /data/mongodb.key
        chmod 400 /data/mongodb.key
        chown 999:999 /data/mongodb.key
        echo 'const isInited = rs.status().ok === 1
        if(!isInited){
          rs.initiate({
              _id: "rs0",
              members: [
                  { _id: 0, host: "mongo:27017" }
              ]
          })
        }' > /data/initReplicaSet.js
        # 启动MongoDB服务
        exec docker-entrypoint.sh "$$@" &

        # 等待MongoDB服务启动
        until mongo -u myusername -p mypassword --authenticationDatabase admin --eval "print('waited for connection')" > /dev/null 2>&1; do
          echo "Waiting for MongoDB to start..."
          sleep 2
        done

        # 执行初始化副本集的脚本
        mongo -u myusername -p mypassword --authenticationDatabase admin /data/initReplicaSet.js

        # 等待docker-entrypoint.sh脚本执行的MongoDB服务进程
        wait $$!

  # fastgpt
  sandbox:
    container_name: sandbox
    image: ghcr.io/labring/fastgpt-sandbox:v4.8.6 # git
    networks:
      - fastgpt
    restart: always
  fastgpt:
    container_name: fastgpt
    image: ghcr.io/labring/fastgpt:v4.8.6 # git
    ports:
      - 3000:3000
    networks:
      - fastgpt
    depends_on:
      - mongo
      - milvusStandalone
      - sandbox
    restart: always
    environment:
      # root 密码，用户名为: root。如果需要修改 root 密码，直接修改这个环境变量，并重启即可。
      - DEFAULT_ROOT_PSW=RCms@Zte3
      # AI模型的API地址哦。务必加 /v1。这里默认填写了OneApi的访问地址。
      - OPENAI_BASE_URL=http://10.56.135.208:3001/v1
      # AI模型的API Key。（这里默认填写了OneAPI的快速默认key，测试通后，务必及时修改）
      - CHAT_API_KEY=sk-iffsKb5MuFcZ9W350b32D83386B54cF59435Ed58E7E558E6
      # 数据库最大连接数
      - DB_MAX_LINK=30
      # 登录凭证密钥
      - TOKEN_KEY=any
      # root的密钥，常用于升级时候的初始化请求
      - ROOT_KEY=root_key
      # 文件阅读加密
      - FILE_TOKEN_KEY=filetoken
      # MongoDB 连接参数. 用户名myusername,密码mypassword。
      - MONGODB_URI=mongodb://myusername:mypassword@mongo:27017/fastgpt?authSource=admin
      # zilliz 连接参数
      - MILVUS_ADDRESS=http://milvusStandalone:19530
      - MILVUS_TOKEN=none
      # sandbox 地址
      - SANDBOX_URL=http://sandbox:3000
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    volumes:
      - ./config.json:/app/data/config.json

  # oneapi
  mysql:
    image: mysql:8.0.36
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - fastgpt
    command: --default-authentication-plugin=mysql_native_password
    environment:
      # 默认root密码，仅首次运行有效
      MYSQL_ROOT_PASSWORD: oneapimmysql
      MYSQL_DATABASE: oneapi
    volumes:
      - ./mysql:/var/lib/mysql
  oneapi:
    container_name: oneapi
    #image: oneapi:v1.0.1
    image: ghcr.io/songquanpeng/one-api:latest
    ports:
      - 3001:3000
    privileged: true
    depends_on:
      - mysql
    networks:
      - fastgpt
    restart: always
    environment:
      # mysql 连接参数
      - SQL_DSN=root:oneapimmysql@tcp(mysql:3306)/oneapi
      # 登录凭证加密密钥
      - SESSION_SECRET=oneapikey
      # 内存缓存
      - MEMORY_CACHE_ENABLED=true
      # 启动聚合更新，减少数据交互频率
      - BATCH_UPDATE_ENABLED=true
      # 聚合更新时长
      - BATCH_UPDATE_INTERVAL=10
      # 初始化的 root 密钥（建议部署完后更改，否则容易泄露）
      - INITIAL_ROOT_TOKEN=fastgpt
      # 修复无法获取gpt3.5令牌错误
      - TIKTOKEN_CACHE_DIR=/data/cache
    volumes:
      - ./oneapi:/data

  m3e-large-api:
    image: registry.cn-hangzhou.aliyuncs.com/fastgpt_docker/m3e-large-api:latest
    container_name: m3e-large-api
    restart: always
    privileged: true
    networks:
      - fastgpt
    ports:
      - 6008:6008
    environment:
      # 修复无法获取gpt3.5令牌错误
      - TIKTOKEN_CACHE_DIR=/data/cache
    volumes:
      - ./oneapi:/data

networks:
  fastgpt:
我的也不行 同样的报错 可以帮忙分析下吗？

**Comment by ENg-122** [comment]
config:backup.yaml
[2024/08/15 11:03:48.038 +08:00] [INFO] [logutil/logutil.go:165] ["Log directory"] [configDir=]
[2024/08/15 11:03:48.042 +08:00] [INFO] [logutil/logutil.go:166] ["Set log file to "] [path=logs/backup.log]
[2024/08/15 11:03:48.044 +08:00] [INFO] [core/backup_impl_create_backup.go:31] ["receive CreateBackupRequest"] [requestId=fdcba654-5ab2-11ef-b802-00163e004048] [backupName=zhujun_milvus] [collections="[]"] [databaseCollections=] [async=false] [force=false] [metaOnly=false]
[2024/08/15 11:03:48.044 +08:00] [INFO] [core/backup_context.go:96] ["{Base:0xc00043a780 MaxSegmentGroupSize:2147483648 BackupCollectionParallelism:4 BackupCopyDataParallelism:128 RestoreParallelism:2 KeepTempFiles:false GcPauseEnable:true GcPauseSeconds:7200 GcPauseAddress:http://localhost:9091}"]
[2024/08/15 11:03:48.044 +08:00] [INFO] [core/backup_context.go:97] ["{Base:0xc00043a780 Enabled:true DebugMode:false SimpleResponse:true}"]
[2024/08/15 11:04:48.112 +08:00] [WARN] [storage/minio_chunk_manager.go:124] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://localhost:9000/a-bucket/?location=\": net/http: timeout awaiting response headers"]
[2024/08/15 11:05:48.318 +08:00] [WARN] [storage/minio_chunk_manager.go:124] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://localhost:9000/a-bucket/?location=\": net/http: timeout awaiting response headers"]
[2024/08/15 11:06:48.778 +08:00] [WARN] [storage/minio_chunk_manager.go:124] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://localhost:9000/a-bucket/?location=\": net/http: timeout awaiting response headers"]
[2024/08/15 11:07:49.582 +08:00] [WARN] [storage/minio_chunk_manager.go:124] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://localhost:9000/a-bucket/?location=\": net/http: timeout awaiting response headers"]
